### DATASOURCE EXAMPLE CONFIGURATIONS FOR COVID19API DATA.
### COPY AND PASTE RESULTING DATASOURCE IDs FOR PIPELINE CONFIGURATION OR CHECK IN UI.


@baseURL = http://localhost:9000/api/adapter/datasources

@country = "germany"

## status = confirmed | recovered | deaths
@status = "recovered"

### Get List Of Countries
POST {{baseURL}}  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://api.covid19api.com/countries",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    },
    "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 60000
  },
  "metadata": {
    "displayName":"covidCountries"
  }
}

### Get List Of Cases Per Country Per Province By Case Type
POST {{baseURL}}  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://api.covid19api.com/country/{{country}}/",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    },
    "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 60000
  },
  "metadata": {
    "displayName":"covidCasesPerCountryPerCase"
  }
}

### Summary of new and total cases per country
POST {{baseURL}}  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://api.covid19api.com/summary",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    },
    "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 60000
  },
  "metadata": {
    "displayName":"covidSummary"
  }
}

### Get List Of Cases Per Country Per Province By Case Type From The First Recorded Case, updated with latest live count
POST {{baseURL}}  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "/dayone/country/{{country}}/status/{{status}}/live",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    },
    "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 60000
  },
  "metadata": {
    "displayName":"covidLive"
  }
}

