@adapterUrl = http://localhost:9000/api/adapter/datasources
@coreUrl = http://localhost:9000/api/core


### Get List Of Countries
POST {{adapterUrl}}  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://api.covid19api.com/countries",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    },
    "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 60000
  },
  "metadata": {
    "displayName":"covidCountries"
  }
}

# paste datasource id from response above here.
# for a fresh install of the ods, the id will be 1.
@dataSourceId = 1

### Store data without modification and trigger a firebase notification
POST {{coreUrl}}/pipelines  HTTP/1.1
Content-Type: application/json

{
  "datasourceId": {{dataSourceId}},
  "transformation":  {
    "func": "return data;"
  },
  "metadata": {
    "displayName":"covid"
  },
  "notifications": [
    {
      "condition": "true",
      "type": "FCM",
      "projectId": "{{fcmProjectId}}",
      "clientEmail": "{{fcmClientEmail}}",
      "privateKey": "{{fcmKey}}",
      "topic": "{{fcmTopic}}"
    }
  ]
}
