@baseURL = http://localhost:9000/api/adapter

### Get all supported protocols
GET {{baseURL}}/protocols  HTTP/1.1
Content-Type: application/json

### Get all supported data formats
GET {{baseURL}}/formats  HTTP/1.1
Content-Type: application/json

### Perform Data Import JSON
POST {{baseURL}}/dataImport  HTTP/1.1
Content-Type: application/json

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations.json",
        "encoding": "UTF-8"
      }
    },
    "format": {
      "type": "JSON",
      "parameters": {}
    }
}

### Perform Data Import CSV
POST {{baseURL}}/dataImport  HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "protocol": {
      "type": "HTTP",
      "parameters": {
        "location": "https://www.bka.de/SharedDocs/Downloads/DE/Publikationen/PolizeilicheKriminalstatistik/2018/BKATabellen/FaelleLaenderKreiseStaedte/BKA-LKS-F-03-T01-Kreise_csv.csv?__blob=publicationFile&v=3",
        "encoding": "ISO-8859-1"
      }
    },
    "format": {
      "type": "CSV",
      "parameters": {
        "columnSeparator": ";",
        "lineSeparator": "\n",
        "skipFirstDataRow": false,
        "firstRowAsHeader": true
      }
    }
}

### Fetch imported data
// Use the id you got in the dataImport response
@dataId = 1

GET {{baseURL}}/data/{{dataId}}  HTTP/1.1
Content-Type: application/json



### Get all datasources
GET {{baseURL}}/datasources  HTTP/1.1

### Create a datasources
POST {{baseURL}}/datasources  HTTP/1.1
Content-Type: application/json

{
  "protocol": {
    "type": "HTTP",
    "parameters": {
      "location": "https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations.json",
      "encoding": "UTF-8"
    }
  },
  "format": {
    "type": "JSON",
    "parameters": {}
  },
  "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 1000
  },
  "metadata": {
    "author": "icke",
    "license": "none"
  }
}

### Delete all datasources
DELETE {{baseURL}}/datasources/ HTTP/1.1

### Get all datasource events
GET {{baseURL}}/datasources/events  HTTP/1.1

### Get latest datasource events
GET {{baseURL}}/datasources/events/latest  HTTP/1.1

@datasourceId = 1
### Get all datasource events for datasource x
GET {{baseURL}}/datasources/events?datasourceId={{datasourceId}}  HTTP/1.1

### Delete datasource x
DELETE {{baseURL}}/datasources/{{datasourceId}} HTTP/1.1

### Update datasource x
PUT {{baseURL}}/datasources/{{datasourceId}} HTTP/1.1
Content-Type: application/json

{
  "protocol": {
    "type": "HTTP",
    "parameters": {
      "location": "https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations.json",
      "encoding": "UTF-8"
    }
  },
  "format": {
    "type": "JSON",
    "parameters": {}
  },
  "trigger": {
    "firstExecution": "2018-10-07T01:32:00.123Z",
    "periodic": true,
    "interval": 1000
  },
  "metadata": {
    "author": "newauthor",
    "license": "AGPL3"
  }
}
