@baseURL = http://localhost:9000/api/core

### Get all pipelines
GET {{baseURL}}/pipelines  HTTP/1.1

### Get pipeline x
@pipelineid = 3
GET {{baseURL}}/pipelines/{{pipelineid}}  HTTP/1.1

### Create a pipeline
POST {{baseURL}}/pipelines  HTTP/1.1
Content-Type: application/json

{
  "datasourceId": 123,
  "transformations": [
    {
      "func": "return data[0];"
    },{
      "func": "data.test = 'abc'; return data;"
    }
  ],
  "metadata": {
    "author": "icke",
    "license": "none"
  },
  "notifications": [
    {
      "condition": "data.test === 'abc'",
      "type": "WEBHOOK",
      "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
    },
    {
      "condition": "typeof data.test === 'string'",
      "type": "FCM",
      "projectId": "{{fcmProjectId}}",
      "clientEmail": "{{fcmClientEmail}}",
      "privateKey": "{{fcmKey}}",
      "topic": "{{fcmTopic}}"
    }
  ]
}


@pipelineId = 11

### Update a pipeline
PUT {{baseURL}}/pipelines/{{pipelineId}}  HTTP/1.1
Content-Type: application/json

{
  "datasourceId": 999,
  "transformations": [
    {
      "func": "return data[0];"
    },{
      "func": "data.test = 'abc'; return data;"
    }
  ],
  "metadata": {
    "author": "icke",
    "license": "none"
  },
  "notifications": [
    {
      "condition": "data.test === 'abc'",
      "type": "WEBHOOK",
      "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
    },
    {
      "condition": "typeof data.test === 'string'",
      "type": "FCM",
      "projectId": "{{fcmProjectId}}",
      "clientEmail": "{{fcmClientEmail}}",
      "privateKey": "{{fcmKey}}",
      "topic": "{{fcmTopic}}"
    }
  ]
}



### Delete all pipelines
DELETE {{baseURL}}/pipelines/ HTTP/1.1
