@baseURL = http://localhost:9000/api/notification
#@baseURL = http://localhost:8080
### Get version
GET {{baseURL}}/version  HTTP/1.1


### Get all notification configs
GET {{baseURL}}/configs  HTTP/1.1
Content-Type: application/json

### Get all notification configs for pipeline
GET {{baseURL}}/configs?pipelineId=17  HTTP/1.1
Content-Type: application/json

### Save notification webhook config
POST {{baseURL}}/configs  HTTP/1.1
Content-Type: application/json

{
  "pipelineId": 17,
  "condition": "true",
  "type": "WEBHOOK",
  "parameter": {
    "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
  }
}

### Get notification config
GET {{baseURL}}/configs/1  HTTP/1.1
Content-Type: application/json

### Edit notification config
PUT {{baseURL}}/configs/1  HTTP/1.1
Content-Type: application/json


{
  "pipelineId": 18,
  "condition": "true",
  "type": "WEBHOOK",
  "parameter": {
    "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
  }
}


### Delete notification config
DELETE {{baseURL}}/configs/1  HTTP/1.1
Content-Type: application/json

### Trigger all notifications of pipeline
POST {{baseURL}}/trigger  HTTP/1.1
Content-Type: application/json

{
  "pipelineId": 17,
  "pipelineName": "Integration-Test Pipeline 2 (not triggering)",
  "data": {
    "value1": 1
  }
}
