@baseURL = http://localhost:9000/api/notification
#@baseURL = http://localhost:8080
### Get version
GET {{baseURL}}/version  HTTP/1.1


### Get all notification configs for pipeline
GET {{baseURL}}/config/pipeline/17  HTTP/1.1
Content-Type: application/json

### Save notification webhook config
POST {{baseURL}}/config/webhook  HTTP/1.1
Content-Type: application/json

{
  "pipelineId": 15,
  "condition": "true",
  "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
}

### Get webhook config
GET {{baseURL}}/config/webhook/1  HTTP/1.1
Content-Type: application/json

### Edit webhook config
PUT {{baseURL}}/config/webhook/10  HTTP/1.1
Content-Type: application/json


{
  "pipelineId": 17,
  "condition": "true",
  "url": "http://www.mocky.io/v2/5dc94f7a2f0000680073eb96"
}


### Delete webhook config
DELETE {{baseURL}}/config/webhook/1  HTTP/1.1
Content-Type: application/json

### Trigger all notifications of pipeline
POST {{baseURL}}/trigger  HTTP/1.1
Content-Type: application/json

{
  "pipelineId": 17,
  "pipelineName": "Integration-Test Pipeline 2 (not triggering)",
  "dataLocation": "http://www.ods.de/data/123",
  "jobResult": {
    "data": {
      "value1": 1
    },
    "stats": {
      "durationInMilliSeconds": 500,
      "startTimestamp": 12345,
      "endTimestamp": 12345
    }
  }
}
