@baseURL = http://localhost:9000/storage
@pipelineId = de1c9f8f-cd86-4edd-b10e-a0fe8762135e 

### Perform Storage Structure Creation
POST {{baseURL}}/rpc/createstructurefordatasource  HTTP/1.1
Content-Type: application/json

{
    "pipelineid": "{{pipelineId}}"
}

### Get Stored Data
GET {{baseURL}}/{{pipelineId}} HTTP/1.1
