apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: {{NAMESPACE}}
  labels:
    app: ods
    service: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: scheduler
  template:
    metadata:
      labels:
        app: ods
        service: scheduler
    spec:
      imagePullSecrets:
      - name: ods-registry-secret
      containers:
      - env:
        - name: ADAPTER_SERVICE_URL
          value: "http://adapter-service:8080"
        - name: PIPELINE_SERVICE_URL
          value: "http://pipeline-service:8080"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-db-service:3000"
        - name: INITIAL_CONNECTION_RETRIES
          value: "20"
        - name: INITIAL_CONNECTION_RETRY_BACKOFF
          value: "5000"
        image: registry.gitlab.com/profoss/open-data-service/ods-main/scheduler:{{IMAGE_TAG}}
        imagePullPolicy: Always
        name: scheduler-service
        resources: {}
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
