apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformation-deployment
  namespace: {{NAMESPACE}}
  labels:
    app: ods
    service: transformation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: transformation
  template:
    metadata:
      labels:
        app: ods
        service: transformation
    spec:
      imagePullSecrets:
      - name: ods-registry-secret
      containers:
      - env:
        image: registry.gitlab.com/profoss/open-data-service/ods-main/transformation:{{IMAGE_TAG}}
        imagePullPolicy: Always
        name: transformation-service
        resources: {}
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
