version: "3.7"

services:
  # ----------------- ADAPTER SERVICE -----------------
  mock-server:
    build: 
      context: ./adapter/integration-test/
      dockerfile: Dockerfile.mocks
    
    environment:
      MOCK_SERVER_PORT: 8080

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-mock-server.rule=PathPrefix(`/api/integration-tests/mock-server/`)"
      - "traefik.http.routers.to-mock-server.middlewares=mock-server-stripprefix@docker"
      - "traefik.http.middlewares.mock-server-stripprefix.stripprefix.prefixes=/api/integration-tests/mock-server"

