export MOCK_SERVER_PORT=8081
export ADAPTER_SERVICE_URL=http://localhost:$MOCK_SERVER_PORT
export SCHEDULER_API=http://localhost:8080
export MOCK_SERVER_API=$ADAPTER_SERVICE_URL
export AMQP_URL=amqp://rabbit_adm:R4bb!7_4DM_p4SS@localhost:5672
export AMQP_CONNECTION_RETRIES=40
export AMQP_CONNECTION_BACKOFF=3
export MAX_TRIGGER_RETRIES=3
export CONNECTION_RETRIES=3
export CONNECTION_BACKOFF_IN_MS=1000
export AMQP_SCHEDULER_EXCHANGE=AMQP_SCHEDULER_EXCHANGE
export AMQP_SCHEDULER_QUEUE=AMQP_SCHEDULER_QUEUE
export AMQP_DATASOURCE_CONFIG_TOPIC=AMQP_DATASOURCE_CONFIG_TOPIC
export AMQP_DATASOURCE_CONFIG_CREATED_TOPIC=AMQP_DATASOURCE_CONFIG_CREATED_TOPIC
export AMQP_DATASOURCE_CONFIG_DELETED_TOPIC=AMQP_DATASOURCE_CONFIG_DELETED_TOPIC
export AMQP_DATASOURCE_CONFIG_UPDATED_TOPIC=AMQP_DATASOURCE_CONFIG_UPDATED_TOPIC

docker-compose -f ../docker-compose.yml up -d rabbitmq
node integration-test/src/mock.adapter.js &
npm run start &
cd integration-test || exit
npm run test && killall node || killall node
