version: '3.7'

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=debezium
      - POSTGRES_PASSWORD=debezium
    command:
      - '-cwal_level=logical'
      - '-cmax_wal_senders=1'
      - '-cmax_replication_slots=1'
    ports:
      - 5432:5432
  rabbitmq:
    image:  rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: 'S0m3_R4bBi7_C0ok13'
      RABBITMQ_DEFAULT_USER: 'rabbit_adm'
      RABBITMQ_DEFAULT_PASS: 'R4bb!7_4DM_p4SS'
    ports:
      - "15672:15672"
      - "5672:5672"
