CONNECTION_RETRIES="30"
CONNECTION_BACKOFF="2000"
POSTGRES_HOST="adapter-db"
POSTGRES_PORT="5432"
POSTGRES_PW="admin"
POSTGRES_USER="adapterservice"
POSTGRES_DB="adapterservice"
AMQP_URL="amqp://rabbit_adm:R4bb!7_4DM_p4SS@rabbitmq:5672"
ADAPTER_AMQP_IMPORT_SUCCESS_TOPIC="datasource.execution.success"
ADAPTER_AMQP_IMPORT_FAILED_TOPIC="datasource.execution.failed"
ADAPTER_AMQP_DATASOURCE_CREATED_TOPIC="datasource.config.created"
ADAPTER_AMQP_DATASOURCE_UPDATED_TOPIC="datasource.config.updated"
ADAPTER_AMQP_DATASOURCE_DELETED_TOPIC="datasource.config.deleted"
ADAPTER_AMQP_ADAPTER_EXCHANGE="ods_global"
ADAPTER_AMQP_DATASOURCE_IMPORT_TRIGGER_QUEUE="adapter.datasource-import-trigger"
ADAPTER_AMQP_DATASOURCE_IMPORT_TRIGGER_QUEUE_TOPIC="datasource.import-trigger.*"
ADAPTER_AMQP_DATASOURCE_IMPORT_TRIGGER_CREATED_TOPIC="datasource.import-trigger.created"
npm run start
