@baseURL = http://localhost:9000

### Pegelonline data for Konstanz
POST {{baseURL}}/core/pipelines HTTP/1.1
Content-Type: application/json

{
  "adapter": {
    "protocol": "HTTP",
    "format": "JSON",
    "location": "https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations/Konstanz?includeTimeseries=true&includeCurrentMeasurement=true"
  },
  "transformations":
    {
      "func": "result = {};result.name = data.shortname;result.timestamp = data.timeseries[0].currentMeasurement.timestamp;result.unit = \"mm\";result.pegel = data.timeseries[0].currentMeasurement.value*1000;return result;"
    },
  "trigger": {
    "firstExecution": "2018-10-15T11:12:00.123",
    "periodic": false,
    "interval": 60000
  },
  "metadata": {
    "author": "Examplicus",
    "license": "ExampleLicense"
  }
}
