name: ODS Adapter Service Build & Test & Publish

on: [push]

jobs:
  adapter-service-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          cd adapter
          docker build -t docker.pkg.github.com/${{ github.repository }}/adapter-service .
      
      - name: Integrationtest
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build adapter-service-it
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d adapter-service
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from adapter-service-it adapter-service-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
    
      - name: Push to registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/adapter-service

          ADAPTER_VERSION=$(cat ./src/main/resources/application.properties | grep "version =" | awk '{print $3}' | sed "s/[']//g")

          docker tag $IMAGE_ID $IMAGE_ID:$ADAPTER_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$ADAPTER_VERSION
          docker push $IMAGE_ID:latest